# Generated by Django 3.1.7 on 2021-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='edad',
            field=models.PositiveIntegerField(verbose_name='edad'),
        ),
    ]
