# Generated by Django 3.1.7 on 2021-03-21 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20210320_0942'),
        ('lector', '0002_auto_20210320_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lector.lector'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_prestamo', to='libro.libro'),
        ),
    ]
