# Generated by Django 3.1.7 on 2021-03-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_auto_20210320_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
        migrations.AlterField(
            model_name='lector',
            name='edad',
            field=models.PositiveIntegerField(verbose_name='edad'),
        ),
    ]
