# Generated by Django 3.1.7 on 2021-03-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20210320_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo', 'fecha'], 'verbose_name': 'libro', 'verbose_name_plural': 'libros'},
        ),
    ]
