# Generated by Django 3.1.7 on 2021-03-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20210321_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
